"""
Seed users for the mock API — 100 users covering every KYC status + tier combo.
Keyed by user_id, email, and phone for O(1) lookup on all three.
"""
from engine.mock_api.models import UserProfile, KYCInfo, KYCStatus, UserTier

# ── Raw seed data ────────────────────────────────────────────────────────────

_SEED: list[dict] = [
    # ── dev_user: local development fallback (no JWT injected yet) ──────────
    {
        "user_id": "dev_user",
        "first_name": "Dev",
        "last_name": "User",
        "email": "dev@bitazza.com",
        "phone": "+66800000000",
        "tier": UserTier.vip,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="ID document is expired",
            reviewed_at="2026-01-10T10:00:00Z",
        ),
    },
    # approved — one per tier
    {
        "user_id": "USR-000001",
        "first_name": "Somchai",
        "last_name": "Rakpong",
        "email": "somchai.rakpong@example.com",
        "phone": "+66812345601",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.approved, kyc_tier=1, reviewed_at="2025-11-01T09:00:00Z"),
    },
    {
        "user_id": "USR-000002",
        "first_name": "Nattaya",
        "last_name": "Suwan",
        "email": "nattaya.suwan@example.com",
        "phone": "+66812345602",
        "tier": UserTier.vip,
        "kyc": KYCInfo(status=KYCStatus.approved, kyc_tier=2, reviewed_at="2025-10-15T14:30:00Z"),
    },
    {
        "user_id": "USR-000003",
        "first_name": "Preecha",
        "last_name": "Kongkiat",
        "email": "preecha.kongkiat@example.com",
        "phone": "+66812345603",
        "tier": UserTier.ea,
        "kyc": KYCInfo(status=KYCStatus.approved, kyc_tier=2, reviewed_at="2025-09-20T08:00:00Z"),
    },
    {
        "user_id": "USR-000004",
        "first_name": "Wanida",
        "last_name": "Phirom",
        "email": "wanida.phirom@example.com",
        "phone": "+66812345604",
        "tier": UserTier.high_net_worth,
        "kyc": KYCInfo(status=KYCStatus.approved, kyc_tier=3, reviewed_at="2025-08-05T11:15:00Z"),
    },
    # rejected — multiple reasons
    {
        "user_id": "USR-000005",
        "first_name": "Tanawat",
        "last_name": "Srisuk",
        "email": "tanawat.srisuk@example.com",
        "phone": "+66812345605",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="ID document is expired",
            reviewed_at="2026-01-10T10:00:00Z",
        ),
    },
    {
        "user_id": "USR-000006",
        "first_name": "Malee",
        "last_name": "Chantra",
        "email": "malee.chantra@example.com",
        "phone": "+66812345606",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Selfie does not match the ID photo",
            reviewed_at="2026-02-03T13:45:00Z",
        ),
    },
    {
        "user_id": "USR-000007",
        "first_name": "Korakot",
        "last_name": "Boonmee",
        "email": "korakot.boonmee@example.com",
        "phone": "+66812345607",
        "tier": UserTier.vip,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Address on proof of residence does not match the registered address",
            reviewed_at="2026-01-28T09:30:00Z",
        ),
    },
    {
        "user_id": "USR-000008",
        "first_name": "Siriporn",
        "last_name": "Nakorn",
        "email": "siriporn.nakorn@example.com",
        "phone": "+66812345608",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Document image is too blurry to verify",
            reviewed_at="2026-03-01T16:00:00Z",
        ),
    },
    # pending_information
    {
        "user_id": "USR-000009",
        "first_name": "Arthit",
        "last_name": "Thongdee",
        "email": "arthit.thongdee@example.com",
        "phone": "+66812345609",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-03-20T08:00:00Z"),
    },
    {
        "user_id": "USR-000010",
        "first_name": "Jintana",
        "last_name": "Wiset",
        "email": "jintana.wiset@example.com",
        "phone": "+66812345610",
        "tier": UserTier.vip,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-03-22T10:00:00Z"),
    },
    # pending_review
    {
        "user_id": "USR-000011",
        "first_name": "Piyawat",
        "last_name": "Ladda",
        "email": "piyawat.ladda@example.com",
        "phone": "+66812345611",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-03-25T12:00:00Z"),
    },
    {
        "user_id": "USR-000012",
        "first_name": "Supansa",
        "last_name": "Panya",
        "email": "supansa.panya@example.com",
        "phone": "+66812345612",
        "tier": UserTier.ea,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-03-26T09:00:00Z"),
    },
    # not_started
    {
        "user_id": "USR-000013",
        "first_name": "Ratchanok",
        "last_name": "Sombat",
        "email": "ratchanok.sombat@example.com",
        "phone": "+66812345613",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000014",
        "first_name": "Kittisak",
        "last_name": "Meechai",
        "email": "kittisak.meechai@example.com",
        "phone": "+66812345614",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    # suspended
    {
        "user_id": "USR-000015",
        "first_name": "Panida",
        "last_name": "Krongkaew",
        "email": "panida.krongkaew@example.com",
        "phone": "+66812345615",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.suspended, reviewed_at="2026-02-14T11:00:00Z"),
    },
    {
        "user_id": "USR-000016",
        "first_name": "Noppadol",
        "last_name": "Saengjan",
        "email": "noppadol.saengjan@example.com",
        "phone": "+66812345616",
        "tier": UserTier.vip,
        "kyc": KYCInfo(status=KYCStatus.suspended, reviewed_at="2026-01-05T15:00:00Z"),
    },
    # expired
    {
        "user_id": "USR-000017",
        "first_name": "Waraporn",
        "last_name": "Chai",
        "email": "waraporn.chai@example.com",
        "phone": "+66812345617",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.expired, reviewed_at="2024-03-01T09:00:00Z"),
    },
    {
        "user_id": "USR-000018",
        "first_name": "Thanakorn",
        "last_name": "Prom",
        "email": "thanakorn.prom@example.com",
        "phone": "+66812345618",
        "tier": UserTier.ea,
        "kyc": KYCInfo(status=KYCStatus.expired, reviewed_at="2024-06-10T14:00:00Z"),
    },
    # high net worth — additional statuses
    {
        "user_id": "USR-000019",
        "first_name": "Lalita",
        "last_name": "Ruangrit",
        "email": "lalita.ruangrit@example.com",
        "phone": "+66812345619",
        "tier": UserTier.high_net_worth,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-03-28T08:00:00Z"),
    },
    {
        "user_id": "USR-000020",
        "first_name": "Veerasak",
        "last_name": "Inthawong",
        "email": "veerasak.inthawong@example.com",
        "phone": "+66812345620",
        "tier": UserTier.high_net_worth,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Source of funds documentation is insufficient",
            reviewed_at="2026-03-15T10:30:00Z",
        ),
    },

    # ── USR-000021–025: approved (simulation pool) ────────────────────────────
    {
        "user_id": "USR-000021",
        "first_name": "Chatri",
        "last_name": "Pattana",
        "email": "chatri.pattana@example.com",
        "phone": "+66812345621",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.approved, kyc_tier=1, reviewed_at="2025-12-10T09:00:00Z"),
    },
    {
        "user_id": "USR-000022",
        "first_name": "Nuch",
        "last_name": "Srisombat",
        "email": "nuch.srisombat@example.com",
        "phone": "+66812345622",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.approved, kyc_tier=1, reviewed_at="2025-11-20T14:00:00Z"),
    },
    {
        "user_id": "USR-000023",
        "first_name": "Anucha",
        "last_name": "Wongpan",
        "email": "anucha.wongpan@example.com",
        "phone": "+66812345623",
        "tier": UserTier.vip,
        "kyc": KYCInfo(status=KYCStatus.approved, kyc_tier=2, reviewed_at="2025-10-05T10:30:00Z"),
    },
    {
        "user_id": "USR-000024",
        "first_name": "Ploy",
        "last_name": "Thammarat",
        "email": "ploy.thammarat@example.com",
        "phone": "+66812345624",
        "tier": UserTier.ea,
        "kyc": KYCInfo(status=KYCStatus.approved, kyc_tier=2, reviewed_at="2025-09-15T08:00:00Z"),
    },
    {
        "user_id": "USR-000025",
        "first_name": "Wanchai",
        "last_name": "Sukhum",
        "email": "wanchai.sukhum@example.com",
        "phone": "+66812345625",
        "tier": UserTier.high_net_worth,
        "kyc": KYCInfo(status=KYCStatus.approved, kyc_tier=3, reviewed_at="2025-08-20T11:00:00Z"),
    },

    # ── USR-000026–045: rejected (simulation pool — varied reasons) ───────────
    {
        "user_id": "USR-000026",
        "first_name": "Decha",
        "last_name": "Phichai",
        "email": "decha.phichai@example.com",
        "phone": "+66812345626",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="ID document is expired",
            reviewed_at="2026-01-12T10:00:00Z",
        ),
    },
    {
        "user_id": "USR-000027",
        "first_name": "Pim",
        "last_name": "Buranakorn",
        "email": "pim.buranakorn@example.com",
        "phone": "+66812345627",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Selfie does not match the ID photo",
            reviewed_at="2026-02-05T13:00:00Z",
        ),
    },
    {
        "user_id": "USR-000028",
        "first_name": "Kritsana",
        "last_name": "Sitthiphon",
        "email": "kritsana.sitthiphon@example.com",
        "phone": "+66812345628",
        "tier": UserTier.vip,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Address on proof of residence does not match the registered address",
            reviewed_at="2026-01-30T09:00:00Z",
        ),
    },
    {
        "user_id": "USR-000029",
        "first_name": "Fon",
        "last_name": "Phuang",
        "email": "fon.phuang@example.com",
        "phone": "+66812345629",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Document image is too blurry to verify",
            reviewed_at="2026-03-02T16:00:00Z",
        ),
    },
    {
        "user_id": "USR-000030",
        "first_name": "Pramote",
        "last_name": "Sukchinda",
        "email": "pramote.sukchinda@example.com",
        "phone": "+66812345630",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Proof of residence is older than 3 months",
            reviewed_at="2026-02-20T11:00:00Z",
        ),
    },
    {
        "user_id": "USR-000031",
        "first_name": "Nam",
        "last_name": "Hongsiri",
        "email": "nam.hongsiri@example.com",
        "phone": "+66812345631",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Name on ID does not match the registered name",
            reviewed_at="2026-03-10T08:30:00Z",
        ),
    },
    {
        "user_id": "USR-000032",
        "first_name": "Wichit",
        "last_name": "Praphan",
        "email": "wichit.praphan@example.com",
        "phone": "+66812345632",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Missing required supporting document",
            reviewed_at="2026-02-14T14:00:00Z",
        ),
    },
    {
        "user_id": "USR-000033",
        "first_name": "Nook",
        "last_name": "Kerdkaew",
        "email": "nook.kerdkaew@example.com",
        "phone": "+66812345633",
        "tier": UserTier.vip,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Photo ID is partially obscured",
            reviewed_at="2026-01-25T10:00:00Z",
        ),
    },
    {
        "user_id": "USR-000034",
        "first_name": "Boonlert",
        "last_name": "Narot",
        "email": "boonlert.narot@example.com",
        "phone": "+66812345634",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Date of birth on ID does not match the registered date",
            reviewed_at="2026-02-28T09:00:00Z",
        ),
    },
    {
        "user_id": "USR-000035",
        "first_name": "Aoy",
        "last_name": "Thipparos",
        "email": "aoy.thipparos@example.com",
        "phone": "+66812345635",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="ID document type not supported",
            reviewed_at="2026-03-05T15:00:00Z",
        ),
    },
    {
        "user_id": "USR-000036",
        "first_name": "Sombat",
        "last_name": "Wattana",
        "email": "sombat.wattana@example.com",
        "phone": "+66812345636",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Selfie lighting is insufficient for verification",
            reviewed_at="2026-01-18T13:00:00Z",
        ),
    },
    {
        "user_id": "USR-000037",
        "first_name": "Mink",
        "last_name": "Tantirat",
        "email": "mink.tantirat@example.com",
        "phone": "+66812345637",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Proof of residence document is not acceptable",
            reviewed_at="2026-02-08T10:00:00Z",
        ),
    },
    {
        "user_id": "USR-000038",
        "first_name": "Chatchai",
        "last_name": "Ponsuk",
        "email": "chatchai.ponsuk@example.com",
        "phone": "+66812345638",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Identity verification failed due to facial recognition mismatch",
            reviewed_at="2026-03-18T11:00:00Z",
        ),
    },
    {
        "user_id": "USR-000039",
        "first_name": "Gift",
        "last_name": "Chuaychoo",
        "email": "gift.chuaychoo@example.com",
        "phone": "+66812345639",
        "tier": UserTier.vip,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Account flagged for enhanced due diligence",
            reviewed_at="2026-01-20T14:00:00Z",
        ),
    },
    {
        "user_id": "USR-000040",
        "first_name": "Tanin",
        "last_name": "Sawasdee",
        "email": "tanin.sawasdee@example.com",
        "phone": "+66812345640",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Duplicate identity detected — possible multiple accounts",
            reviewed_at="2026-02-22T09:00:00Z",
        ),
    },
    {
        "user_id": "USR-000041",
        "first_name": "Pear",
        "last_name": "Promma",
        "email": "pear.promma@example.com",
        "phone": "+66812345641",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="ID document is expired",
            reviewed_at="2026-03-08T10:00:00Z",
        ),
    },
    {
        "user_id": "USR-000042",
        "first_name": "Somsak",
        "last_name": "Jaturon",
        "email": "somsak.jaturon@example.com",
        "phone": "+66812345642",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Selfie does not match the ID photo",
            reviewed_at="2026-02-17T13:00:00Z",
        ),
    },
    {
        "user_id": "USR-000043",
        "first_name": "View",
        "last_name": "Piriyapan",
        "email": "view.piriyapan@example.com",
        "phone": "+66812345643",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Source of funds documentation is insufficient",
            reviewed_at="2026-01-15T11:00:00Z",
        ),
    },
    {
        "user_id": "USR-000044",
        "first_name": "Mongkol",
        "last_name": "Kanchana",
        "email": "mongkol.kanchana@example.com",
        "phone": "+66812345644",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Background of selfie contains personal information",
            reviewed_at="2026-03-22T15:00:00Z",
        ),
    },
    {
        "user_id": "USR-000045",
        "first_name": "Bow",
        "last_name": "Siriwan",
        "email": "bow.siriwan@example.com",
        "phone": "+66812345645",
        "tier": UserTier.regular,
        "kyc": KYCInfo(
            status=KYCStatus.rejected,
            rejection_reason="Document image is too blurry to verify",
            reviewed_at="2026-02-10T09:00:00Z",
        ),
    },

    # ── USR-000046–060: pending_information (simulation pool) ─────────────────
    {
        "user_id": "USR-000046",
        "first_name": "Suchart",
        "last_name": "Praman",
        "email": "suchart.praman@example.com",
        "phone": "+66812345646",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-03-28T08:00:00Z"),
    },
    {
        "user_id": "USR-000047",
        "first_name": "Joy",
        "last_name": "Kaewkla",
        "email": "joy.kaewkla@example.com",
        "phone": "+66812345647",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-03-29T10:00:00Z"),
    },
    {
        "user_id": "USR-000048",
        "first_name": "Witoon",
        "last_name": "Thammasak",
        "email": "witoon.thammasak@example.com",
        "phone": "+66812345648",
        "tier": UserTier.vip,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-03-27T09:00:00Z"),
    },
    {
        "user_id": "USR-000049",
        "first_name": "Kwan",
        "last_name": "Watcharapong",
        "email": "kwan.watcharapong@example.com",
        "phone": "+66812345649",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-04-01T08:00:00Z"),
    },
    {
        "user_id": "USR-000050",
        "first_name": "Aran",
        "last_name": "Krairoek",
        "email": "aran.krairoek@example.com",
        "phone": "+66812345650",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-04-02T11:00:00Z"),
    },
    {
        "user_id": "USR-000051",
        "first_name": "Orn",
        "last_name": "Suwanrat",
        "email": "orn.suwanrat@example.com",
        "phone": "+66812345651",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-03-30T14:00:00Z"),
    },
    {
        "user_id": "USR-000052",
        "first_name": "Narin",
        "last_name": "Mahajan",
        "email": "narin.mahajan@example.com",
        "phone": "+66812345652",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-04-03T09:00:00Z"),
    },
    {
        "user_id": "USR-000053",
        "first_name": "Pat",
        "last_name": "Piriyapan",
        "email": "pat.piriyapan@example.com",
        "phone": "+66812345653",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-03-31T10:00:00Z"),
    },
    {
        "user_id": "USR-000054",
        "first_name": "Prasit",
        "last_name": "Hongsiri",
        "email": "prasit.hongsiri@example.com",
        "phone": "+66812345654",
        "tier": UserTier.ea,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-04-04T08:00:00Z"),
    },
    {
        "user_id": "USR-000055",
        "first_name": "Wan",
        "last_name": "Ponsuk",
        "email": "wan.ponsuk@example.com",
        "phone": "+66812345655",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-04-01T13:00:00Z"),
    },
    {
        "user_id": "USR-000056",
        "first_name": "Yuthana",
        "last_name": "Wattana",
        "email": "yuthana.wattana@example.com",
        "phone": "+66812345656",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-03-26T11:00:00Z"),
    },
    {
        "user_id": "USR-000057",
        "first_name": "Bee",
        "last_name": "Chuaychoo",
        "email": "bee.chuaychoo@example.com",
        "phone": "+66812345657",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-04-05T09:00:00Z"),
    },
    {
        "user_id": "USR-000058",
        "first_name": "Narong",
        "last_name": "Sawasdee",
        "email": "narong.sawasdee@example.com",
        "phone": "+66812345658",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-04-02T14:00:00Z"),
    },
    {
        "user_id": "USR-000059",
        "first_name": "Jub",
        "last_name": "Thammarat",
        "email": "jub.thammarat@example.com",
        "phone": "+66812345659",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-04-06T08:00:00Z"),
    },
    {
        "user_id": "USR-000060",
        "first_name": "Chai",
        "last_name": "Krairoek",
        "email": "chai.krairoek@example.com",
        "phone": "+66812345660",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_information, reviewed_at="2026-04-03T10:00:00Z"),
    },

    # ── USR-000061–075: pending_review (simulation pool) ─────────────────────
    {
        "user_id": "USR-000061",
        "first_name": "Santi",
        "last_name": "Promma",
        "email": "santi.promma@example.com",
        "phone": "+66812345661",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-01T08:00:00Z"),
    },
    {
        "user_id": "USR-000062",
        "first_name": "Nipa",
        "last_name": "Wongpan",
        "email": "nipa.wongpan@example.com",
        "phone": "+66812345662",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-02T09:00:00Z"),
    },
    {
        "user_id": "USR-000063",
        "first_name": "Pitak",
        "last_name": "Sukhum",
        "email": "pitak.sukhum@example.com",
        "phone": "+66812345663",
        "tier": UserTier.vip,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-03-30T11:00:00Z"),
    },
    {
        "user_id": "USR-000064",
        "first_name": "Orapin",
        "last_name": "Sitthiphon",
        "email": "orapin.sitthiphon@example.com",
        "phone": "+66812345664",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-03T08:00:00Z"),
    },
    {
        "user_id": "USR-000065",
        "first_name": "Anuwat",
        "last_name": "Pattana",
        "email": "anuwat.pattana@example.com",
        "phone": "+66812345665",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-04T10:00:00Z"),
    },
    {
        "user_id": "USR-000066",
        "first_name": "Suda",
        "last_name": "Kanchana",
        "email": "suda.kanchana@example.com",
        "phone": "+66812345666",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-01T14:00:00Z"),
    },
    {
        "user_id": "USR-000067",
        "first_name": "Chinawat",
        "last_name": "Jaturon",
        "email": "chinawat.jaturon@example.com",
        "phone": "+66812345667",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-05T09:00:00Z"),
    },
    {
        "user_id": "USR-000068",
        "first_name": "Naphat",
        "last_name": "Siriwan",
        "email": "naphat.siriwan@example.com",
        "phone": "+66812345668",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-02T11:00:00Z"),
    },
    {
        "user_id": "USR-000069",
        "first_name": "Kritsada",
        "last_name": "Thammasak",
        "email": "kritsada.thammasak@example.com",
        "phone": "+66812345669",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-06T08:00:00Z"),
    },
    {
        "user_id": "USR-000070",
        "first_name": "Pavinee",
        "last_name": "Kerdkaew",
        "email": "pavinee.kerdkaew@example.com",
        "phone": "+66812345670",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-03T13:00:00Z"),
    },
    {
        "user_id": "USR-000071",
        "first_name": "Tanadon",
        "last_name": "Watcharapong",
        "email": "tanadon.watcharapong@example.com",
        "phone": "+66812345671",
        "tier": UserTier.vip,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-01T10:00:00Z"),
    },
    {
        "user_id": "USR-000072",
        "first_name": "Saowaluk",
        "last_name": "Narot",
        "email": "saowaluk.narot@example.com",
        "phone": "+66812345672",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-04T09:00:00Z"),
    },
    {
        "user_id": "USR-000073",
        "first_name": "Witthaya",
        "last_name": "Phuang",
        "email": "witthaya.phuang@example.com",
        "phone": "+66812345673",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-05T11:00:00Z"),
    },
    {
        "user_id": "USR-000074",
        "first_name": "Wipada",
        "last_name": "Tantirat",
        "email": "wipada.tantirat@example.com",
        "phone": "+66812345674",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-02T14:00:00Z"),
    },
    {
        "user_id": "USR-000075",
        "first_name": "Nai",
        "last_name": "Praman",
        "email": "nai.praman@example.com",
        "phone": "+66812345675",
        "tier": UserTier.ea,
        "kyc": KYCInfo(status=KYCStatus.pending_review, reviewed_at="2026-04-06T10:00:00Z"),
    },

    # ── USR-000076–087: not_started (simulation pool) ─────────────────────────
    {
        "user_id": "USR-000076",
        "first_name": "Bussaba",
        "last_name": "Srisombat",
        "email": "bussaba.srisombat@example.com",
        "phone": "+66812345676",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000077",
        "first_name": "Surin",
        "last_name": "Phichai",
        "email": "surin.phichai@example.com",
        "phone": "+66812345677",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000078",
        "first_name": "Chalida",
        "last_name": "Buranakorn",
        "email": "chalida.buranakorn@example.com",
        "phone": "+66812345678",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000079",
        "first_name": "Arun",
        "last_name": "Sawasdee",
        "email": "arun.sawasdee@example.com",
        "phone": "+66812345679",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000080",
        "first_name": "Daranee",
        "last_name": "Sukchinda",
        "email": "daranee.sukchinda@example.com",
        "phone": "+66812345680",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000081",
        "first_name": "Krit",
        "last_name": "Praphan",
        "email": "krit.praphan@example.com",
        "phone": "+66812345681",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000082",
        "first_name": "Suda",
        "last_name": "Wattana",
        "email": "suda.wattana@example.com",
        "phone": "+66812345682",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000083",
        "first_name": "Pirat",
        "last_name": "Jaturon",
        "email": "pirat.jaturon@example.com",
        "phone": "+66812345683",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000084",
        "first_name": "Manee",
        "last_name": "Promma",
        "email": "manee.promma@example.com",
        "phone": "+66812345684",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000085",
        "first_name": "Somkid",
        "last_name": "Thipparat",
        "email": "somkid.thipparat@example.com",
        "phone": "+66812345685",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000086",
        "first_name": "Ratree",
        "last_name": "Kanchana",
        "email": "ratree.kanchana@example.com",
        "phone": "+66812345686",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },
    {
        "user_id": "USR-000087",
        "first_name": "Phongsak",
        "last_name": "Piriyapan",
        "email": "phongsak.piriyapan@example.com",
        "phone": "+66812345687",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.not_started),
    },

    # ── USR-000088–094: suspended (simulation pool) ───────────────────────────
    {
        "user_id": "USR-000088",
        "first_name": "Sawai",
        "last_name": "Hongsiri",
        "email": "sawai.hongsiri@example.com",
        "phone": "+66812345688",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.suspended, reviewed_at="2026-02-01T10:00:00Z"),
    },
    {
        "user_id": "USR-000089",
        "first_name": "Kannika",
        "last_name": "Siriwan",
        "email": "kannika.siriwan@example.com",
        "phone": "+66812345689",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.suspended, reviewed_at="2026-01-15T11:00:00Z"),
    },
    {
        "user_id": "USR-000090",
        "first_name": "Wutthichai",
        "last_name": "Suwanrat",
        "email": "wutthichai.suwanrat@example.com",
        "phone": "+66812345690",
        "tier": UserTier.vip,
        "kyc": KYCInfo(status=KYCStatus.suspended, reviewed_at="2026-02-20T09:00:00Z"),
    },
    {
        "user_id": "USR-000091",
        "first_name": "Phattharaphon",
        "last_name": "Krairoek",
        "email": "phattharaphon.krairoek@example.com",
        "phone": "+66812345691",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.suspended, reviewed_at="2026-03-01T14:00:00Z"),
    },
    {
        "user_id": "USR-000092",
        "first_name": "Sirinart",
        "last_name": "Mahajan",
        "email": "sirinart.mahajan@example.com",
        "phone": "+66812345692",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.suspended, reviewed_at="2026-01-28T10:00:00Z"),
    },
    {
        "user_id": "USR-000093",
        "first_name": "Praween",
        "last_name": "Thammasak",
        "email": "praween.thammasak@example.com",
        "phone": "+66812345693",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.suspended, reviewed_at="2026-02-10T13:00:00Z"),
    },
    {
        "user_id": "USR-000094",
        "first_name": "Nalinrat",
        "last_name": "Phuang",
        "email": "nalinrat.phuang@example.com",
        "phone": "+66812345694",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.suspended, reviewed_at="2026-03-05T09:00:00Z"),
    },

    # ── USR-000095–100: expired (simulation pool) ─────────────────────────────
    {
        "user_id": "USR-000095",
        "first_name": "Pongpat",
        "last_name": "Watcharapong",
        "email": "pongpat.watcharapong@example.com",
        "phone": "+66812345695",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.expired, reviewed_at="2024-04-01T09:00:00Z"),
    },
    {
        "user_id": "USR-000096",
        "first_name": "Thanyarat",
        "last_name": "Narot",
        "email": "thanyarat.narot@example.com",
        "phone": "+66812345696",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.expired, reviewed_at="2024-05-15T14:00:00Z"),
    },
    {
        "user_id": "USR-000097",
        "first_name": "Soraphon",
        "last_name": "Tantirat",
        "email": "soraphon.tantirat@example.com",
        "phone": "+66812345697",
        "tier": UserTier.vip,
        "kyc": KYCInfo(status=KYCStatus.expired, reviewed_at="2024-03-10T10:00:00Z"),
    },
    {
        "user_id": "USR-000098",
        "first_name": "Rungthiwa",
        "last_name": "Ponsuk",
        "email": "rungthiwa.ponsuk@example.com",
        "phone": "+66812345698",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.expired, reviewed_at="2024-06-20T08:00:00Z"),
    },
    {
        "user_id": "USR-000099",
        "first_name": "Thanadol",
        "last_name": "Chuaychoo",
        "email": "thanadol.chuaychoo@example.com",
        "phone": "+66812345699",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.expired, reviewed_at="2024-07-05T11:00:00Z"),
    },
    {
        "user_id": "USR-000100",
        "first_name": "Pensri",
        "last_name": "Sawasdee",
        "email": "pensri.sawasdee@example.com",
        "phone": "+66812345700",
        "tier": UserTier.regular,
        "kyc": KYCInfo(status=KYCStatus.expired, reviewed_at="2024-08-10T13:00:00Z"),
    },
]

# ── Indexes (built once at import time) ──────────────────────────────────────

_BY_ID: dict[str, UserProfile] = {}
_BY_EMAIL: dict[str, UserProfile] = {}
_BY_PHONE: dict[str, UserProfile] = {}

for _u in _SEED:
    _profile = UserProfile(**_u)
    _BY_ID[_profile.user_id] = _profile
    _BY_EMAIL[_profile.email.lower()] = _profile
    _BY_PHONE[_profile.phone] = _profile


def get_by_user_id(user_id: str) -> UserProfile | None:
    return _BY_ID.get(user_id)


def get_by_email(email: str) -> UserProfile | None:
    return _BY_EMAIL.get(email.lower().strip())


def get_by_phone(phone: str) -> UserProfile | None:
    return _BY_PHONE.get(phone.strip())
